# Generated by Django 5.0.8 on 2024-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demping", "0002_remove_product_concurents_remove_product_in_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="best_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="recomendation_price",
            field=models.IntegerField(),
        ),
    ]
